name: Testing
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        python setup.py install
        ./test.sh
